name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Backend setup and test
      - name: Install backend dependencies
        run: npm install
        working-directory: Inspire-Blog

      - name: Run backend tests
        run: npm test
        working-directory: Inspire-Blog

      # Frontend setup and test
      - name: Install frontend dependencies
        run: npm install
        working-directory: Inspire-Blog

      - name: Run frontend tests
        run: npm test
        working-directory: Inspire-Blog
